%%--------------------------------------
% DRUG RESISTANCE REPORT
%%--------------------------------------

\documentclass{article}

% Install packages here

\usepackage[letterpaper]{geometry}
\usepackage{Sweave}
\usepackage{fancyhdr}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage[table]{xcolor}
\usepackage{tabu}
\usepackage{collcell}
\usepackage{multirow}
\usepackage[skins]{tcolorbox}
\usepackage{fontspec}

%----- ESTABLISH COMMANDS HERE

% For column U, defined as right of left margin
\newcolumntype{U}{>{\collectcell\MakeUppercase}l<{\endcollectcell}}

\tcbuselibrary{listings,breakable}

%bounding box for report sections
\newtcolorbox{reportSection}[2][]{%
  attach boxed title to top left
  			   = {xshift=10pt, yshift=-8pt},
  colback      = white!5!white,
  colframe     = white!75!black,
  fonttitle    = \bfseries,
  colbacktitle = white,
  title        = \textbf{\large{#2}},
  coltitle	   = black,
  arc = 0mm,
  opacityframe = 0.5,
  boxrule=1pt,
  boxed title style={%
    sharp corners, 
    rounded corners=northwest, 
    colback=white, 
    boxrule=0pt,
    titlerule=0mm},
  enhanced,
}


%----- MAKE HEADER + FOOTER

%HEADER
%HEADER TEXT
\pagestyle{fancy}
\fancyhf{}
\renewcommand{\headrulewidth}{0pt}

% HEADER TEXT
\lhead{\Large{\textbf{MYCOBACTERIUM TUBERCULOSIS\\ RESISTANCE REPORT}} \\ \normalsize{UNDER DEVELOPMENT}}
\chead{}
\rhead{\includegraphics[scale=0.25]{data/LogoDesign}}

% FOOTER

\lfoot{Page \thepage\ of 2}
\rfoot{Patient ID: \Sexpr{reportData$BARCODE} | DATE: \Sexpr{reportData$reportDate} | LOCATION: \Sexpr{reportData$reportLab} }


% ------- Start of document

\begin{document}
\SweaveOpts{concordance=TRUE}

\tabulinesep=5pt
\noindent 
\taburulecolor{lightgray}
\noindent \begin{tabu} to \textwidth {|XU||XU|}
\hline

% PATIENT TABLE

<<patientInfoTab, results=tex, echo=FALSE>>=
cat("Patient Name &",paste(reportData$FName,reportData$LName, sep=" "), "& Barcode &",reportData$BARCODE,"\\\\ \\hline ")
cat("DOB &", reportData$DOB, "& NHI Number &",reportData$NHI,"\\\\ \\hline ")
cat("Location &", reportData$Location, "& Sample Type &", reportData$sType,"\\\\ \\hline ")
#cat("Sample Source &", reportData$sSource, "& Sample Date &", reportData$sDate,"\\\\ \\hline ")
#cat("Sample ID &", reportData$sID, "& Sample Type &", reportData$sampleType,"\\\\ \\hline ")
#cat("Reporting Lab &", reportData$reportLab,"& Report Date &", reportData$reportDate,"\\\\ \\hline ")
#cat("Requested By &", reportData$requestor,"& Requester Contact &", reportData$reqContact,"\\\\ \\hline ")
@

\end{tabu}
\vspace{5mm}
% SECTION 1

\begin{reportSection}{Summary}

\vspace{1mm}

<<sec1:summaryTextGen, echo=FALSE, results=tex>>=


#Drug Resistance Summary
tmp<-drugDat %>% filter(Status == "Resistant")

if(nrow(tmp) == 0){
  rDrugStat<-"It is predicted to be \\textbf{susceptible to all drugs}. "
}else{
  nItem<-nrow(tmp)
  syntaxNice<-NULLif(nItem == 1){
    syntaxNice<-tmp$Drug
  }else if(nItem == 2){
    syntaxNice<-paste(tmp$Drug,collapse=" and ")
  }else{
    syntaxNice<-paste(paste(tmp$Drug[1:(nrow(tmp)-1)],collapse=", "),tmp$Drug[nrow(tmp)],sep=", and ")
  }

  rDrugStat<-sprintf("It is prediced to be \\textbf{resistant to %s}/ ",syntaxNice)
}

# Make Summary Sentence
cat(paste(rDrugStat))


@

\end{reportSection}
\vspace{5mm}

% Can do summary for detected lineage and organism here

% Drug Susceptibility Report
<<sec2:drugFunction,echo=FALSE,results=tex>>=

susceptData<-function(drugDat=NULL,class=NULL){
  fLineS<-filter(drugDat,Class == class) %>% filter(Status == "Sensitive")
  fLineR<-filter(drugDat,Class == class) %>% filter(Status == "Resistant")
  
  #Sensitive drugs
  if(nrow(fLineS) > 0){
    for(i in 1:nrow(fLineS)){
      #Special line
      if(i == nrow(fLineS)){
        if(nrow(fLineR)==0){
          cat(sprintf("\\multirow{-%d}{*}{%s}",i,class),sprintf("& \\multirow{-%d}{*}{Susceptible} &",i), fLineS[i,]$Drug, "&", fLineS[i,]$Details, "\\\\")
        }else{
          cat(sprintf(" & \\multirow{-%d}{*}{Susceptible} &",i), fLineS[i,]$Drug, "&", fLineS[i,]$Details, "\\\\")
        }
      }else{
        cat(" & &", fLineS[i,]$Drug, "&", fLineS[i,]$Details, "\\\\")
      }
    }
  }

  # Drug Resistance
  if(nrow(fLineR) > 0){
    for(i in 1:nrow(fLineR)){
      #Special line
      if(i == nrow(fLineR)){
        cat(sprintf("\\multirow{-%d}{*}{%s}",nrow(fLineS)+nrow(fLineR),class),sprintf("& \\cellcolor[HTML]{EFEFEF} \\multirow{-%d}{*}{Resistant} &",i),"\\cellcolor[HTML]{EFEFEF}",fLineR[i,]$Drug, "&", "\\cellcolor[HTML]{EFEFEF}",fLineR[i,]$Details, "\\\\")
      }else{
        cat(" & \\cellcolor[HTML]{EFEFEF} &","\\cellcolor[HTML]{EFEFEF}",fLineR[i,]$Drug, "&","\\cellcolor[HTML]{EFEFEF}",fLineR[i,]$Details, "\\\\")
      }
    }
  }
}

# Tick box summary
drugSusceptTickBox<-function(drugDat=NULL){
  tickStatus<-data.frame(threshold = c(0,1,2,"2+"),
                         status = c("No drug resistance predicted",
                                    "Mono-resistance predicted",
                                    "Multi-drug resistance predicted",
                                    "Extensive drug resistance predicted"
                                    ),
                         stringsAsFactors = FALSE
                         )
  nResist <- drugDat %>% filter(Status == "Resistant") %>% count()
  nResist <- nResist$n
  
  if(nresist>2)
    nresist = "2+"
  
  for(i in 1:nrow(tickStatus)){
    status<-NULLif(tickStatus[i,]$threshold == nResist){
      status<-paste("& \\cellcolor[HTML]{EFEFEF} $\\text{\\rlap{$\\checkmark$}}\\square$",tickStatus[i,]$status,"\\\\")
    }else{
      status<-paste("&$\\square$",tickStatus[i,]$status,"\\\\")
    }
    
    cat(status)
  }
}

@

\begin{reportSection}{Drug Susceptibility}

\vspace{1mm}

\tabulinesep=2pt
\noindent
\taburulecolor{lightgray}
\noindent \begin{tabu} to \textwidth {X[1.1,l]X}

% Tick boxed
\multirow{4}{*}{\parbox{7.3cm}{\footnotesize{Resistance is reported when a high-confidence resistance-conferring mutation is detected. \textbf{``No mutation detected'' does not exclude the possibility of resistance}}}}

<<sec2:susceptibilityTickBox, echo=FALSE, results=tex>>=
drugSusceptTickBox(drugDat)
@
\end{tabu}
\vspace{3mm}

\tabulinesep=5pt
\noindent
\taburulecolor{lightgray}
\noindent \begin{tabu} to \textwidth {X[0.5,l]X[0.75,l]X[0.75,l]X[2,l]}
\hline
Drug class & Interpretation & Drug & Resistance Gene \scriptsize{(Amino Acid Mutation)} \\
\cline{1-4}
<<sec2:susceptibilityTestFirstLine, echo=FALSE, results=tex>>=
susceptData(drugDat,class="First-line")
@
\cline{1-4}
<<sec2:susceptibilityTestSecondLine,echo=FALSE,results=tex>>=
susceptData(drugDat,class="Second-line")
@
\end{tabu}
\end{reportSection}

% Additional comments

\begin{reportSection}{Assay Details}
\vspace{1mm}
\tabulinesep=5pt
\noindent
\taburulecolor{lightgray}
\noindent \begin{tabu} to \textwidth {|XU||XU|}
\hline
% BASED ON ISO15189 reporting standards

Sample ID & A12345    & Barcode   &     \\ \hline
Sequencer & Illumina HiSeq 2500   & Method    & WGS     \\ \hline
Pipeline  & Resistance v.0.1a   & Reference   & H37Rv     \\ \hline

\end{tabu}
\vspace{1mm}

\end{reportSection}
\vspace{1mm}

% Additional comments part 2

\begin{reportSection}{Comments}
\vspace{1mm}

\footnotesize{\Sexpr{reportData$comments}}
\vspace{2mm}

\textcolor{gray}{\footnotsize{\textit{\textbf{Standard Disclaimer:} Low frequency hetero-resistance below the limit of detection by sequencing may affect typing results.  The interpretation provided is based on the current understanding of genotype-phenotype relationships.}}}

\end{reportSection}
\vspace{1mm}

% Autherisation

\begin{reportSection}{Authorised}

\vspace{1mm}
\tabulinesep=5pt
\noindent
\taburulecolor{lightgray}
\noindent \begin{tabu} to \textwidth {|XU||XU|}
\hline

Signature & & Name  & \\ \hline
Position  & & Date  &   \\ \hline

\end{tabu}

\end{reportSection}

\end{document}